### ISSUE TITLE
Handle both randomization/randomseedshift and randomization/permutationseed

### ISSUE THREAD

**Issue by gasse** [ds4dm/ecole#14]
Currently, `Model.seed()` only sets `randomization/randomseedshift`. The permutation of rows / cols depends on a distinct seed, "randomization/permutationseed". We have to deal with that in `Model`, so that users only have to change one seed, which then affects both. I suggest setting both of them to the same value, or a shifted value, e.g.,
`randomization/permutationseed = randomization/randomseedshift + 42`

**Comment by AntoinePrv** [comment]
As per a previous discussion with you (few weeks ago already), we agreed to remove `Model.seed` as to not impose what seeding means.

As of this commit, there is a method that the user can override to define what seeding means.
https://github.com/ds4dm/ecole/blob/ecd0ae3e5f11ef35084a20a8f25e519a4671d938/libecole/include/ecole/environment/default.hpp#L220

We can change what the defaults parameters are. If you feel this is resolved, I let you close the issue.

**Comment by gasse** [comment]
Sounds good, although I find the name a bit confusing. It is not only about seeding, but more deciding on how to randomize (permutation, no permutation). And also not any state can be randomized. Only the initial state.

Maybe that's fine for now, we'll see when actually using ecole how the whole API feels.

**Comment by AntoinePrv** [comment]
Outdated, see #29
