### ISSUE TITLE
Default IndependentSet parameters not the same as in Gasse et al. (2019)

### ISSUE THREAD

**Issue by AntoinePrv** [ds4dm/ecole#140]
## Describe the bug

I noticed that for all but the independent set instances, the default settings in Ecole are the same as reported in Gasse (https://arxiv.org/pdf/1906.01629.pdf). But for independent set, Gasse report affinity=4 and 500 nodes for training. But the default settings in Ecole are 100 nodes and affinity=5.

cc @gizarp 

## Expected behavior
Keep the same setting as in Gasse et al. (2019).

## Additional context
@gasse @dchetelat Should we change it, or leave it as is?

**Comment by dchetelat** [comment]
I would switch it to the Gasse et al. default, to be consistent with the other generators.

**Comment by jdumouchelle** [comment]
Made the changes in branch `v0.6.x`
