### ISSUE TITLE
Instance saving error for python<3.8

### ISSUE THREAD

**Issue by th-yoon** [ds4dm/ecole#161]
## Describe the problem or improvement suggested

On python<3.8, it emits error when saving experts samples with pickle; 
as introduced in https://github.com/ds4dm/ecole/blob/master/examples/branching-imitation.ipynb

## Describe the solution you would like

On python>=3.8, the error disappears. 

## Describe alternatives you have considered

Adding requirement of python>=3.8 might help users of this package.

## Additional context

![image](https://user-images.githubusercontent.com/54887560/115355932-1ddd4800-a1f6-11eb-9c10-7cddda4da6a4.png)

**Comment by kevin031060** [comment]
It helps!

**Comment by th-yoon** [comment]
@kevin031060 glad it helped!

**Comment by AntoinePrv** [comment]
Thank you @th-yoon @kevin031060 for reaching out.

The tutorial has been updated for the pickle support added, which was added in 'Ecole>=0.6' recently.
Could you confirm you have the latest version of Ecole when you encounter the problem. If that's the case, could you share the Error message you are getting.

**Comment by th-yoon** [comment]
@AntoinePrv Yes I have the latest version of Ecole, and the error message is like..
`Can't pickle NodeBipartite object`

**Comment by AntoinePrv** [comment]
I cannot reproduce your issue (on Linux)

I have 
```bash
$ python --version
Python 3.7.0

$ python -m ecole.version
Ecole version info:
    Version       : 0.6.0
    Git Revision  : 3c2f6b0cd474ad9ed50f328726c88a2da0606089
    Build Type    : Release
    Build OS      : Linux-4.15.0-1111-azure
    Build Time    : 2021-04-15T13:06:18
    Build Compiler: GNU-9.3.0
Built against SCIP:
    Version       : 7.0.2
```
