### ISSUE TITLE
Minor test bugfixes

### ISSUE THREAD

**Issue by gasse** [ds4dm/ecole#167]
https://github.com/ds4dm/ecole/blob/2201252db3427786b437174e2a0541aa47e29bc7/libecole/tests/src/dynamics/test-branching.cpp#L36

This test does not seem right. Shouldn't we have:
```
REQUIRE(var_ids.size() <= model.lp_columns().size());
```
instead ?

**Comment by AntoinePrv** [comment]
Sounds right, thanks!
