### ISSUE TITLE
StrongBranchingScores should return a vector of length nb_vars, not nb_cols

### ISSUE THREAD

**Issue by dchetelat** [ds4dm/ecole#200]
In general, `nb_cols <= nb_vars`, and most of the time `nb_cols == nb_vars`, but it has been brought to my attention by Maxime that the definition of pseudo candidates makes sense even if no LP has been construction, which can be seen in how SCIP determines that a variable is a pseudo candidate:
https://scipopt.org/doc/html/branch_8c_source.php#l00788

So I would propose to change StrongBranchingScores to now use variables instead of columns.

**Comment by gasse** [comment]
Relates to #134

**Comment by AntoinePrv** [comment]
+1 for #134
I'm getting less and less sure now with `SCIPvarGetProbindex`, `SCIPcolGetIndex`, and now `SCIPcolGetLPPos` that there isn't a screw-up somewhere (let alone in user code).
