### ISSUE TITLE
Primal / dual integral code review

### ISSUE THREAD

**Issue by gasse** [ds4dm/ecole#202]
Why not using a logical OR (&) to check for event types, as the SCIP codebase does ?
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L133
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L137

Shouldn't we check for the objective direction here ? (minimization vs maximization instances)
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L101
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L118
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L245

Won't this cause an issue if more that one bound reward function objects are used within an environment ?
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L214

Could the event handler pointer be returned here ?
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L249

The initial primal bound here should not be needed:
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L165

~~Shouldn't we use the initial dual bound here ?~~
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L170

~~Same here, shouldn't we use the initial primal bound instead ?~~
https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L186

**Comment by gasse** [comment]
Never mind my three last comments, I finally understood. I think the parameters should be renamed `primal_bound_offset` and `dual_bound_offset` though, and should take an initial value of 0.

**Comment by gasse** [comment]
For both the `PrimalIntegral` and `DualIntegral`, what about changing the parameter names to `(offset, initial_primal_bound)` and `(offset, initial_dual_bound)` ? That seems more explicit to me. Then, the `PrimalDualIntegral` would be `(initial_primal_bound, initial_dual_bound)` which is consistent.

**Comment by jdumouchelle** [comment]
> Could the event handler pointer be returned here ?
> 
> https://github.com/ds4dm/ecole/blob/3704f0ccb7a03242293b67169b2d411eb26abe04/libecole/src/reward/boundintegral.cpp#L249
> 

This is the only change I did not make.  It believe it could be returned here, but we would need to take care of the casting that `add_eventhdlr` already does.  I also think it is less intuitive to return the event handler from the function `add_eventhdlr`

**Comment by gasse** [comment]
Addressed in #204
