### ISSUE TITLE
can ecole use cplex/gurobi as options for LP solvers during the Branching process?

### ISSUE THREAD

**Issue by stardustwls** [ds4dm/ecole#258]
## Describe the problem or improvement suggested
For some kinds of problems, the speed of ecole is too slow to do some deep research, especially the LP solver during the B&B process.

## Describe the solution you would like
pyscipopt allow us to use cplex/gurobi instead of soplex as the LP solver, could you please tell us the possibility of solving this problem? Thanks a lot.

**Comment by AntoinePrv** [comment]
The LP solver is controlled by your SCIP (the C library) installation. If you install SCIP with Cplex/Gurobi as the LP solver, then yes, I don't see why you wouldn't be able to. The Ecole code would remain the same.

For having different LP solvers in the conda-forge SCIP package, the [package repo](https://github.com/conda-forge/scipoptsuite-feedstock) (that we co-maintain) is the proper place to discuss that. But given that Cplex and Gurobi are commercial, I don't see an easy way.

*Disclaimer*: We have not tested different LP solvers ourselves, let us know if you find bugs.

**Comment by gasse** [comment]
Hi @stardustwls , @samiit ,

There is an in-between alternative which works with Ecole in principle: interfacing with SCIP, but then exchange SCIP's default LP solver (SoPLEX) for another, more competitive LP solver (see a list [here](https://www.scipopt.org/doc/html/LPI.php)). I've recently tried using Gurobi's LP solver, it worked like a charm. What you have to do basically is to first compile the full [SCIP Optimization Suite](https://www.scipopt.org/doc/html/md_INSTALL.php) using CMake, with a specific `LPS` option to change the default backend LP solver. Then, with SCIP is properly installed and set-up, you can simply compile Ecole and Pyscipopt from source as follows:
```bash
# path to Scip installation
SCIPOPTDIR="$HOME/opt/scipoptsuite-7.0.3"

# path to where to put the compiled python packages (wheels)
mkdir -p $HOME/wheels

# set up a build virtual environment
virtualenv --no-download ./build-env
source ./build-env/bin/activate
pip install cython
pip install wheel
pip install numpy
pip install scikit-build
pip install cmake
pip install pytest
pip install pytest-helpers-namespace

# build PySCIPOpt
git clone git@github.com:scipopt/PySCIPOpt.git
cd PySCIPOpt
python setup.py bdist_wheel --dist-dir $HOME/wheels
cd ..

# build ecole
git clone git@github.com:ds4dm/ecole.git
cd ecole
python setup.py bdist_wheel --dist-dir $HOME/wheels
cd ..

# remove build environment
deactivate
rm -r ./build-env
```

Let us know if that helps,

Best,
Maxime

**Comment by AntoinePrv** [comment]
@gasse if I may adjust: except for conda, neither PySCIPOpt nor Ecole provide a libscip installation. They will find the one installed, whether it uses Soplex, Gurobi,... as an LP solver (understand it makes not difference for them).
Hence regular install instruction apply for both PySCIPOpt and Ecole.
