### ISSUE TITLE
Parameter values are silently rounded in Configuring environment

### ISSUE THREAD

**Issue by gasse** [ds4dm/ecole#27]
Code to reproduce:
```
import ecole

env = ecole.environment.Configuring()
env.reset(filename='libecole/tests/data/enlight8.mps')
env.step({'presolving/maxrounds': 0.1})
```

I suggest we check types more carefully, e.g., with a narrow cast:
```
template<class Target, class Source>
Target narrow_cast(Source v) {
    auto r = static_cast<Target>(v);
    if (static_cast<Source>(r) != v)
        throw Exception("narrow_cast<>() failed");
    return r;
```

**Comment by AntoinePrv** [comment]
Another option I saw was [this SO answer](https://codereview.stackexchange.com/a/26496).

A few more lines but:
- Has the opportunity to give meaningful exceptions (overflow/underflow/signess);
- Only exists for numbers, so possible to avoid criptic messages with `char` `string` and `const char*` `bool`

**Comment by gasse** [comment]
I was actually going in that direction as well. I agree, templates with enable_if checks would allow for a cleaner implementation of our casting system I feel.
https://github.com/gasse/ecole/blob/configuring-dev/libecole/include/ecole/scip/model.hpp#L205
https://github.com/gasse/ecole/blob/configuring-dev/libecole/include/ecole/scip/model.hpp#L235

**Comment by AntoinePrv** [comment]
Is this the behavior we wanted? Any numerical loss, including rounding from a `double` to a `float` throw an exception, not only overflow/underflow.
