### ISSUE TITLE
Seeding environment / trajectories

### ISSUE THREAD

**Issue by AntoinePrv** [ds4dm/ecole#29]

**Comment by AntoinePrv** [comment]
### OpenAI Gym behavior
In [OpenAI Gym](https://gym.openai.com/), at least in `CartPole-v0`, the behavior is the following:
- `env.seed()` is not a getter but seeds with a random value (time or something else);
- The seed is used to initialize a [MT19937](https://en.wikipedia.org/wiki/Mersenne_Twister) random engine;
- The engine is kept from one trajectory to another (call to `reset`).

### Implications in OpenAI Gym
The engine has periodicity `2^19937`, much larger than the `2^64` (?) possible seed values.
The implications are:
- It is not possible to extract an existing seed (because it does not make sense, only the random state can define the futures sampling operations);
- Some initial states **cannot be accessed by directly seeding**;
- In particular, it means that _Use case C_ is not possible

### In SCIP
SCIP uses the [KISS](https://en.wikipedia.org/wiki/KISS_(algorithm)) with `2^123` periodicity, and `2^31` possible seeds ([implementation](https://scip.zib.de/doc-7.0.0/html/misc_8c.php#ab3b176121315d7063522186b3310a795)).

### In Ecole
Assuming SCIP is the only source of randomness (so far), I see two implementation we could do:
1. Seed SCIP on every episode (`reset`), hence reducing the sampling space, but making it possible to replay individual episode. This requires deciding on a way to get seed `n+1` from seed `n`
2. Use a `int128` as a seed for every episode and basically map it to the SCIP random state (feels hacky to me, break abstraction by mixing concepts, and won't work if SCIP changes algorithm).
3. Similarily to OpenAI Gym, reuse the SCIP random state from one episode to another. To satisfy _Use Case C_, we could expose SCIP random state (get **and** set) so that is possible to replay an episode for debugging. You can also do this in OpenAI Gym, the attribute is not even marked private.

**Comment by gasse** [comment]
I would go for your point 3, which is similar to my solution 2). Something like this:
 - `env.seed(value) -> value` sets the environment seed to value, and returns it.
 - `env.seed() -> value` use the current RNG to generate a seed value, and calls `env.seed(value)`.

Solves all of our concerns, and keeps a simple OpenAI-user-friendly API. This way we indeed limit ourselves to 2^32 distinct episodes, but I guess that's fine.

**Comment by AntoinePrv** [comment]
>  - env.seed(value) -> value sets the environment seed to value, and returns it.
>  - env.seed() -> value use the current RNG to generate a seed value, and calls env.seed(value).

This is indeed compatible with the OpenAi Gym API.

> This way we indeed limit ourselves to 2^32 distinct episodes, but I guess that's fine.

@gasse I think this is not compatible with my point 3. In my view there are two issues (not completely independent issues) here:
- The interface presented to set the seed, mostly addressed by your https://github.com/ds4dm/ecole/issues/29#issuecomment-608086786
- What happens when `reset`ing and no seed is set, which is more what my https://github.com/ds4dm/ecole/issues/29#issuecomment-608706000 is focusing on

My point 3. is not compatible with episode seeds, and yields `2^123` initial states, not all accessible via a seed. To mitigate this, I suggest either exposing the random state, or that the user manually seed at every episode.

**Comment by dchetelat** [comment]
Okay after playing around with a bunch of different possibilities I think I came up with something I like enough to propose as Ecole's seeding system. It requires only minimal changes compared to what we have right now. In fact the code is even shortened.

## Properties

1. `env.seed()` returns (and does not modify) the current seed, while `env.seed(value)` sets the seed to this value.
```
> env = ecole.environment.Branching()
> env.seed()
541686889
> env.seed()
541686889
> env.seed(3)
> env.seed()
3
```
This is slightly inconsistent with how OpenAI gym does things but I don't think it's particularly confusing. It's just a getter/setter.

2. The environment is seeded randomly by default.
```
> env = ecole.environment.Branching()
> env.seed()
541686889
> env = ecole.environment.Branching()
> env.seed()
9325811
```

3. Just like in Gym, any transition changes the seed, and any stochasticity depends entirely on the seed.
```
> env = ecole.environment.Branching()
> obs, done = env.reset('instance_1.lp')
> env.seed(3)
> obs, *_ = env.step(0)
> env.seed()
1535162761
> obs, done = env.reset('instance_1.lp')
> env.seed(3)
> new_obs, *_ = env.step(0)
> (obs.row_feat == new_obs.row_feat).all()
True
```
This makes it super easy to replay trajectories.

4. The seed can be fed directly in PySCIPOpt to reproduce behavior (!!)
```
> env = ecole.environment.Branching()
> seed = env.seed()
> seed
1156738957
> model = scip.Model()
> model.readProblem('instance_1.lp')
> model.setBoolParam("randomization/permuteconss", True);
> model.setBoolParam("randomization/permutevars", True);
> model.setIntParam("randomization/permutationseed", seed);
> model.setIntParam("randomization/randomseedshift", seed);
> model.setIntParam("randomization/lpseed", seed);
```
This will produce exactly the same behavior in PySCIPopt as in Ecole!

## Internal behavior

I make this work as follow. Let `f(seed)` be a random number generator, producing a trajectory `f_1(seed), f_2(seed), f_3(seed), ...` when called repeatedly (in practice I picked a Mersenne twister). This trajectory is deterministic for a given seed (the generator is usually seeded with `time(NULL)` to achieve actual pseudo-random behavior -- standard stuff).

Then I propose that when calling `env.seed(seed)`, the seed is set to `seed` (duh), and evolves as
`seed, f_1(seed), f_2(seed), f_3(seed), ...` as step/reset is repeatedly called. This leads to all the desired behavior above.

**Comment by dchetelat** [comment]
I also attach above a potential pull request for this seeding system. I understand @AntoinePrv intended to refactor this code anyways, but I think it's useful to look at the [code changes](https://github.com/ds4dm/ecole/pull/44/commits/ce9b166f4c92e10698d5f3cd2c60a8464e9316a2), which are very minimal. Hopefully you will like it. :-)

**Comment by AntoinePrv** [comment]
The environment as a random generator that is then used by the `Dynamics` to initialize new seeds 
https://github.com/ds4dm/ecole/blob/760af59a76f5addb2d947ccba1b60ece3f3710a6/libecole/include/ecole/environment/dynamics.hpp#L48

THe environment does not have a getter for the seed (because it does not make sense and is confusing), but the SCIP seeds used can be accessed (and overriden) using `env.state.model.get_param("random/whatever").
