### ISSUE TITLE
when will ecole support SCIP 8.0.0 version

### ISSUE THREAD

**Issue by xtjjyygy** [ds4dm/ecole#333]
## Describe the problem or improvement suggested

Hello, I would like to ask, when will ecole support SCIP 8.0.0 version, as far as I know, SCIP 7.0.3 version is currently supported, thank you

**Comment by AntoinePrv** [comment]
Hi @xtjjyygy, It already does since version `0.8.0`. If you install with `conda`, you'll get that SCIP version.
