### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Wuwuww** [ds4dm/ecole#336]
## Describe the bug

When I tried to install Ecole with Conda, It shows that：PackagesNotFoundError: The following packages are not available from current channels:
I also tried answer in #329, install Ecole with mamba, but It shows that:
Encountered problems while solving:
  - nothing provides requested ecole
## Setting
- OS: MacOS-M1

**Comment by AntoinePrv** [comment]
Yes, because we do not currently support M1 Macs for Ecole.
In the meantime, you can launch your development environment with Rosetta.
