### ISSUE TITLE
Example corrupts with segmentation fault.

### ISSUE THREAD

**Issue by ben-xj** [ds4dm/ecole#342]
## Describe the bug

When running the example `ecole/examples/configuring-bandits/example.ipynb`, the program corrupts saying "3807 segmentation fault", either when training or evaluating.

## Setting
- OS: MacOS
- Compiler: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
- Python version: Python 3.8.13
- Ecole version: 0.7.3

## To Reproduce

simply by running `conda install -c conda-forge ecole pyscipopt`, and running the example script, i received the error above.

## Expected behavior

the program running without corruption.., which i succeeded once, when setting the `test_n_bids` to 150.

## Additional context

pyscipopt                 3.4.0
scip                      7.0.3

**Comment by gasse** [comment]
Hi @ben-xj , could you try again with the latest version of ecole (0.8.1) ?

**Comment by ben-xj** [comment]
> Hi @ben-xj , could you try again with the latest version of ecole (0.8.1) ?

Thanks, it works!
