### ISSUE TITLE
Observation = None and done = True when using from_file method

### ISSUE THREAD

**Issue by rezabayani** [ds4dm/ecole#354]
[Reposting this from discussions as I believe it is a bug rather than a feature]
Hi,
My Ecole (v8) is having trouble reading observations from the optimization model stored as mps file. Basically, it returns None observation and True done flag when I reset the environment. I did the same approach with Ecole v7 and it was okay back then. Interestingly, when I tried feeding other mps files found online, it is okay with some of them and not with others. I have attached 2 images. Number 1 is when Ecole is acting as intended, using an mps model found online. Number 2 is when Ecole is acting funny, with an mps file I generated myself and was okay with Ecole v7.

![ecole_correct](https://user-images.githubusercontent.com/59495621/222301762-fa51b5df-882d-4fca-b412-6b282f00a2ab.PNG)

![ecole_incorrect](https://user-images.githubusercontent.com/59495621/222301757-a2e07fef-ac5c-43f9-ab73-f964d07ee240.PNG)

_Originally posted by @rezabayani in https://github.com/ds4dm/ecole/discussions/353_

**Comment by rezabayani** [comment]
The mps files to reproduce the results are attached here:
[mps_format.zip](https://github.com/ds4dm/ecole/files/10868713/mps_format.zip)

**Comment by rezabayani** [comment]
Update: I think I have found the cause of this behavior. It appears that SCIP gets rid of some variables in the presolve stage (although I tried disabling presolve actions through setting maxrestarts, maxrounds, abortfac, and restartminred to 0). Therefore, I do not belive this is an issue with Ecole and rather how SCIP's root node is formed.

**Comment by orestiskaitezidis** [comment]
Hi @rezabayani could you please elaborate how you disable the presolve stage eventually? Did you use specific scip_parameters in the env.reset() function? Thank you!
