### ISSUE TITLE
libgcc issue during installation

### ISSUE THREAD

**Issue by nguyenminhtuong** [ds4dm/ecole#363]
## Describe the bug

![image](https://github.com/ds4dm/ecole/assets/32364151/bcd26d11-ad11-4afb-b29b-350930472f1c)

(base) tuong@ANPHATPC:/mnt/c/Users/ADMIN$ conda install -c conda-forge ecole
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.35=0
  - feature:|@/linux-64::__glibc==2.35=0
  - ecole -> libgcc-ng[version='>=9.4.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.35

## Setting
- OS: 
- Compiler: 
- Python version:
- Ecole version:

**Comment by AntoinePrv** [comment]
You should try the installation using [Mamba](https://mamba.readthedocs.io/en/latest/) as a replacement to Conda.

**Comment by nguyenminhtuong** [comment]
I have been able to install ecole but i need to make a fresh conda environment using python 3.8 or 3.9. 

After that I can install ecole using conda. 

So I think this issue should be closed

But may I ask, how to install ecole using mamba ?
