### ISSUE TITLE
Add support for pseudo branching candidates

### ISSUE THREAD

**Issue by dchetelat** [ds4dm/ecole#45]
The branching environments should be able to toggle between using regular, fractional branching candidates (`SCIPgetLPBranchCands`) as hardcoded right now in Ecole, and using all non-fixed variables (`SCIPgetPseudoBranchCands`), which is what learn2branch uses. We will need it to reproduce learn2branch in Ecole.

**Comment by AntoinePrv** [comment]
Solved in 03f8bc5
