### ISSUE TITLE
API for Action set

### ISSUE THREAD

**Issue by AntoinePrv** [ds4dm/ecole#46]
Some environment, such as selecting the branching variable or the next branching node, have a dynamic action set. This means that, within **different states of the episode**, the set of possible action changes.

This is not the same as the *Action Space* defined by OpenAi Gym because the latter is a static property of the environment and does not change during an episode (or between episodes).

The set of available actions is critical information that needs to be given to the user.

Here are some ideas I could think of, none is perfect. Any other ideas are welcome.

### Option 1
The action set is returned as part of the transition in `step` and `reset`
```python
obs, action_set, reward, done, info = env.step(action)
```
Downsides:
  - That's starting to be a lot of thing in a tuple. I myself already have to make efforts to remember if it is `..., reward, done, ...`, or `..., done, reward, ...`, this will add much more confusion.
  - Degrades API for environment that don't need an action set.

### Option 2
An attribute of the environment. Something in the like of 
```python
action = user_policy(obs, env.current_action_set())
obs, reward, done, info = env.step(action)
```
Downsides:
  - More implicit. Does not clearly tell the user that there is complexity to pay attention to. Nor does it tell the user when it changes (is it every episode? very transition?)

### Option 3
Part of the Observation. After all, this is a POMDP, if the observation is not good enough to tell that agent what to do, it is not a good observation, period.
Some thoughts
   - For branching, `NodeBipartite` could have a flag for every variable indicating which variable is fractional, which would have the benefit of avoiding having permutation issues with the action set.
   - However, this is would be different for another observation, e.g. _KhalilState_.
   - What of `NodeBipartite` for other environments, now it needs to contain all action spaces?

**Comment by gasse** [comment]
I like option 3. Either return that information in `obs`, or in `info`. Having it in `obs` makes a lot of sense IMO. `obs` can be a tuple, and we just append the list of available branching candidates to it. ALso, with `obs` as a tuple, it gets easier to ask for several observation functions, would be super flexible for python users.

**Comment by AntoinePrv** [comment]
With `info`, you have to note that it is not returned in `reset`.

**Comment by AntoinePrv** [comment]
So I for one am not a big fan of tuple, especially when they get big.
The way with stronger typing is to return a object (or struct) without any methods that just hold the data. That way, you get an explicit name for all the members.

So something like:
```python
from typing import Any, Dict
import dataclasses


@dataclasses.dataclass
class Transition:
    observation: Any 
    action_set: Any
    reward: float
    done: bool
    info: Dict[str, Any]


class Environment:
    def step(self, action):
        ...
        return Transition(observation=observation, reward=reward, ...)
```
And use with
```python
transition = env.step(action)
new_action = policy(transition.observation)
```

Now you may be thinking it completely breaks with the OpenAi API in unnecessary ways.
However, if we add

```python
class Transition:
    ...

    def __iter__(self):
        yield self.observation
        yield self.reward
        yield self.done
        yield self.info
```
Then the following will work as well because `Transition` is iterable
```python
obs, reward, done, info = env.step(action)
```

**Comment by dchetelat** [comment]
I'm fine with either option 1 or option 3. However, I'm not sure what the advantages are of defining a class for transitions (yet again another class! by the way that class just looks like a fancy `namedtuple`.)
If only to avoid yet again having another class, I would have a preference for option 3. Let's use native Python types as much as possible.

**Comment by AntoinePrv** [comment]
I'm pointing out that tuples and dictionaries are not the only data structure in Python.
Classes also don't need to have methods, they can simply hold data together like C-style struct, with advantages over named tuple.

Ironically, if OpenAI Gym had returned a structured object here, we could have added a field without breaking the interface 🤷 

Not saying saying this is worth it here, just standing up against class bashing. Using classes to hold data is an explicit, self-documenting, way to hold data (read from [attrs](https://www.attrs.org/en/stable/why.html)).

**Comment by AntoinePrv** [comment]
During the implementation, things on the C++ side started to get a bit heavy, because action set on terminal states can also be undefined (_e.g._ if the model is solved, we cannot extract branching candidates). So now we also have optional, if you have a tensor action set, now you easily get:
```c++
std::tuple<..., nonstd::optional<xt::xtensor<..>>, ...>
```

I noticed that on terminal state, the action set, by condtruction, has to `None`.
Now that means the API is over-parametrized and we should always have `action_set == None` when `done == True`.

Another option would therefore to replace the `done` flag by the action_set.
```python
obs, reward, action_set, info = env.step(...)
```
Because objects evaluate to `True` and `None` to `False`, we can even not break API with OpenAI Gym on this:
```python
while action_set:
    obs, reward, action_set, info = env.step(...)
```

There are some caveats. If there is no explicit action set, then we need to return something that evaluate to `True`, could be `True` itself or just a string like `"All actions are allowed"`

Maybe a little more conceptual, but I like that it can be well anchored in the theory: a _terminal state_ is a state on which the set of actions is empty.
