### ISSUE TITLE
Assertions ignored in CI

### ISSUE THREAD

**Issue by AntoinePrv** [ds4dm/ecole#47]
Due to the fact that SCIP and Ecole are compiled in Release mode in CI, all assertions are silently ignored in CI tests.
This is problematic, especially since SCIP relies heavily on it.

- Find the culprit `CMAKE_BUILD_TYPE`? conda `CXX_FLAGS`?

**Comment by gasse** [comment]
Do you mean the C `assert()` ?

**Comment by AntoinePrv** [comment]
Closing because we re now using SCIP from Conda that only have release build so far, so there is no easy way to check this for now.
