### ISSUE TITLE
Compare against default SCIP

### ISSUE THREAD

**Issue by gasse** [ds4dm/ecole#55]
## Describe the problem of improvement suggested
Provide a way to compare against a default SCIP baseline, in terms of Ecole metrics (reward functions).

## Describe the solution you'd like
A new environment (DefaultSCIP ? Default ?) with a single step MDP, and empty action set. That way SCIP is ran with default config, and one can extract Ecole reward functions to compare to other Environments. That DefaultSCIP environment could simply be a specialization of the Configuring environment, with an empty action set.

## Describe alternatives you've considered
Simply using the Configuring environment to provide a default baseline. This can be a bit confusing for users though.

**Comment by AntoinePrv** [comment]
Similarly, I don't think everything has to be an environment. The core idea of an environment is for an agent to _interact_ with it. If we're going to leave almost everything unused, maybe this is not the right abstraction.

Fortunately, the point of having clean, modular, abstractions such as the `RewardFunction` means not only that we can swap the reward in an environment, but also that we can use rewards elsewhere.

Something like the following could be added in only a few lines.
```python
reward = ecole.evaluate_reward("path/to/prob", MyRewardFunction())
```

**Comment by gasse** [comment]
Ok then maybe we could build a complete system, a solver, by combining an environment and a policy ? We could provide default ones, where the policy is anchored within the solver (`strong branching`), and allow users to compose solvers with custom policies. Then `solver.run("path/to/prob")` with simply unfold the MDP.

**Comment by AntoinePrv** [comment]
Now that #56 is closed I don't thing there's much more to do here.
