### ISSUE TITLE
Obtain an initial reward along with the initial observation (`env.reset()`)

### ISSUE THREAD

**Issue by gasse** [ds4dm/ecole#56]
## Describe the problem of improvement suggested
Some environment MDPs may be over after reset(), without any call to step(). In such a case, no reward is available. This is annoying, as typically one would like to obtain cumulated rewards for every episode of the MDP, for example when benchmarking different policies. This situation happens often for example in branching, when the instance is solved in preprocessing. We still want to measure the running time, or the number of nodes, or the primal-dual integral etc.

## Describe the solution you'd like
`observation, action_set, reward, done = env.reset("path/to/problem")`

## Describe alternatives you've considered
Obtaining the cumulated reward at any moment by calling `env.getCumulatedReward()`. However, that cumulated reward would not match a cumulated reward manually computed by the user. Observing such a difference can be very confusing for users. Also, it introduces an additional function, which must be safe-guarded (can be called only during / after an episode).

## Additional context
-

**Comment by AntoinePrv** [comment]
This looks like a hack and feels very confusing to me.
Are you bringing this only as a solution to #55 or can you think of other use cases?

It is important to be able to track metrics and evaluate SCIP defaults but I think this is forcing the "_everything is an environment, everything is a reward_" too much.

**Comment by gasse** [comment]
It is not just about comparing to default SCIP (#55). It is also about dealing with episodes of length 1, where no action is taken. This happens, for example, in the branching environment.

This is not a hack to me, it is consistent with our needs. We already don't stick to the OpenAI gym API for reset, since we have a `done` flag. This flag is necessary for us, to deal with the exact same issue: length-1 episodes which occur in our use cases. Having a `reward` along with `done` in `reset()` is IMO very consistent. Also, our rewardfunctions take a state as input, and give a reward. The initial state `s0` is a state just like any state, and I do not see an inconsistency in obtaining rewards for the initial state. This initial reward can just be 0, and we fall back to the "no initial reward" behaviour of OpenAI.

**Comment by AntoinePrv** [comment]
But what do you do with a reward on episode of length 1 _where no action have been taken_?
I do not know of any algorithm that can run without taking a single action.

For that matter, I also don't think there's not much to be done with instances where `done` is `True` on `reset`, except discarding them.
For me that flag was mostly a courtesy to the user so that they don't end up running on a dataset where 80% of instances would be trivially solved.

It really sounds to me like you are looking for a metric, not a reward.

**Comment by gasse** [comment]
> But what do you do with a reward on episode of length 1 where no action have been taken? I do not know of any algorithm that can run without taking a single action.

At learning, there is nothing to be done with a length-one episode, indeed.
At evaluation however, probably you want to keep that episode in the aggregated results. Say your evaluation criteria is the running time, or the primal-dual integral, measured over 10 instances x 5 seeds. One instance may by chance be solved by presolving, for one of the seeds. Then most likely you want to include that run in your evaluation benchmark, which is, say, the expected running time.

> For that matter, I also don't think there's not much to be done with instances where done is True on reset, except discarding them.
> For me that flag was mostly a courtesy to the user so that they don't end up running on a dataset where 80% of instances would be trivially solved.
I think we discussed that already. Not having that flag returned by `reset` means you assume all episodes have length > 1, which we can not guarantee in some environments, such as branching. An instance may be solved in presolving. That flag is not a courtesy to the user, we just cannot do without it.

> It really sounds to me like you are looking for a metric, not a reward.
What is the difference ? If you aim at optimize a particular metric (running time, number of nodes, primal-dual integral), then it makes a lot of sense to use that metric as a reward to be maximized via RL. The aim of ECOLE is to formulate the learning problems arising inside a solver as MDPs, such that the metric you optimize for translates naturally into a reward function, and you can apply vanilla RL algorithms to optimize that metric.

Another argument for having an initial reward is that it makes it possible to match the cumulated reward with standard metrics such as running time, number of nodes, or primal-dual integral. It makes the formulation of the learning problems as MDPs more natural, and one can simply report the total episode rewards, without having to think about "oh wait, the presolving time is not counted in the cumulated reward, I have to call that other method to collect it". Not having to mention that we would end up having to ducplicate the code for computing metrics and rewards, when these are measuring exactly the same thing.

I do not see any objective issue with having an initial reward. The learning algorithms can just ignore it. The reward functions which do not have an initial reward can just return 0, or even None to warn users there is no such thing.

Finally, we already have that `done` flag in `reset`, which differs from OpenAI gym. Having a `reward` along with `done` is just more consistent.

What do you think?

**Comment by AntoinePrv** [comment]
I think we should let rewards be rewards, and if they're designed to match a specific metric, then I would let the user properly evaluate that metric independently.

> I think we discussed that already. Not having that flag returned by reset means you assume all episodes have length > 1, which we can not guarantee in some environments, such as branching. An instance may be solved in presolving. That flag is not a courtesy to the user, we just cannot do without it.

The other solution for me would have been to throw an Exception.  This `done` flag is like an error code to me. Ecole is meant to _interact_ with environments, if there is no interaction, there nothing to study.
I don't understand why you would you want to add to your measurements instances for which you did not do anything.
If you compare against another baseline, you would literally be comparing the same thing.

-------------

An a more general note, Ecole is not, and should not be, the only way to interact with problem instances. There's PyScipOpt as well.
There is already a lot of work in Ecole, and I don't want to overfill it with every idea we have. I prefer to focus on a some core features and do them well.

There's also a lot of `None`, zeros... in Ecole and I think it's not far from becoming a complete mess.

Is there no way you can achieve what you need by combining Ecole with PySCIPOpt?
All components in Ecole are pretty straightforward to reuse.

If a clear pattern emerges, I'd be open to reconsider.
