### ISSUE TITLE
Rename the EnvironmentComposer Python class

### ISSUE THREAD

**Issue by gasse** [ds4dm/ecole#75]
## Describe the problem or improvement suggested
In the documentation, we talk about environments, while referring to the class EnvironmentComposer. This can be confusing, as it could suggest there is actually an Environment class somewhere, but this class is nowhere to be found.

## Describe the solution you would like
Change the Python class name EnvironmentComposer to Environment.

## Describe alternatives you have considered
Have a proper Environment class, which inherits from EnvironmentComposer ?

## Additional context
NA

**Comment by AntoinePrv** [comment]
For consistency, I would do the same renaming in C++, no?

My only worry is that user are tempted to use the `Environment` class directly. Perhaps, we could make an explicit check
```python
class Environment:
    def __init__(self, ...):
        if self.__Dynamics__ is None:
            raise RuntimeError("This is an abstract class, you probably want to instanciate a specific environment such as `Branching`")
```

Or better,  get Python to do it for us, using `abc.ABC`, and making `__Dynamics__` an abstract class method.

**Comment by gasse** [comment]
Yes, I agree with both the points you raised. Environment should be an abstract class, both in Python and C++.
