### ISSUE TITLE
Bad handling of SCIP time limits

### ISSUE THREAD

**Issue by dchetelat** [ds4dm/ecole#98]
## Describe the bug
When setting time limits with SCIP's `limits/time` parameter, if the time limit occurs when solving an LP, SCIP will return a `LP not solved to optimality` error code, which will be turned into a python exception by Ecole. If the time limit occurs when not solving an LP, SCIP will stop the solving process with a no-issue error code, which won't lead to an exception. Thus, hitting time limits will sometimes raise exceptions, sometimes not, seemingly randomly from the perspective of the user.

## Setting
- OS: Linux
- SCIP: 7.0.1
- Ecole: Latest Ecole

## To Reproduce

```python
import ecole

time_limit = 30 # 30 seconds, say
instance = 'instance.lp'

scip_parameters = {'separating/maxrounds': 0, 'presolving/maxrestarts': 0,
                   'limits/time': time_limit, 'timing/clocktype': 2}
env = ecole.environment.Branching(observation_function=ecole.observation.Pseudocosts(),
                                  scip_params=scip_parameters)
env.seed(3119319000)

observation, action_set, _, done, _ = env.reset(instance)
while not done:
    scores = observation
    action = action_set[scores[action_set].argmax()]
    observation, action_set, _, done, _ = env.step(action)
    done = True
```
The instance can be downloaded [here](https://github.com/ds4dm/ecole/files/5466212/instance.txt), just change the extension from `.txt` to `.lp`.

## Expected behavior
I think if SCIP stopped due to a time limit, it shouldn't raise an exception, regardless of the error code.
Or at minimum, it should be coherent (e.g. always raise an exception or never raise one.)

**Comment by dchetelat** [comment]
I should add that this occurs with the `Branching` environment but doesn't seem to occur with the `Configuring` environment.

**Comment by gasse** [comment]
https://scipopt.org/doc-7.0.1/html/branch__fullstrong_8c_source.php#l00257

Looks like SCIP handles this with SCIPisSolved()
https://scipopt.org/doc-7.0.1/html/group__GeneralSCIPMethods.php#ga0f8f9f0c1f566564e6224e35a9839b74

**Comment by gasse** [comment]
Related issue:
https://github.com/ds4dm/ecole/issues/69

**Comment by gasse** [comment]
https://scipopt.org/doc-7.0.1/html/solve_8c_source.php#l00118

**Comment by AntoinePrv** [comment]
Looks like we can check [`SCIPgetStatus`](https://scipopt.org/doc-7.0.1/html/group__GeneralSCIPMethods.php#ga69a83c2a9d7204ed9fadc6ad2f254916) to check why SCIP is terminating.

**Comment by AntoinePrv** [comment]
This was was actually simpler than expected. The error did not come from the reverse control, or `SCIPsolve`, but simply from computing the action set when it was not allowed.

**Comment by gasse** [comment]
Good job !

**Comment by AntoinePrv** [comment]
I'm releasing `v0.4.4` if you need that bugfix
